[CORE-27] add csp header
broadinstitute/thurloe pull request #334
Opened 2024-10-19 02:07 UTC by kevinmarete

Jira: https://broadworkbench.atlassian.net/browse/CORE-27

**Description:**

This PR adds a Content Security Policy (CSP) header to the Thurloe Swagger page and endpoints to enhance security by reducing the risk of cross-site scripting (XSS) and data injection attacks.

**Testing:**

- Added tests for csp header and ran them successfully 
- Compiled project and observed no issues

---

- [ ] **Submitter**: Make sure Swagger is updated if API changes
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them

2024-10-19 02:08 UTC, kevinmarete commented on src/main/resources/application.conf
> +
Tests were failing due to this missing reference.

2024-10-19 02:10 UTC, kevinmarete commented on src/main/scala/thurloe/Main.scala
> +    binding <- Http().newServerAt("0.0.0.0", 8000).bind(addCSP(routes.route)).recover {
Added CSP header to all routes!

2024-10-19 02:11 UTC, kevinmarete commented on src/main/scala/thurloe/service/ThurloeServiceActor.scala
> +      }
Added CSP header to Swagger Page!

2024-10-19 02:11 UTC, kevinmarete commented on src/main/scala/thurloe/service/ThurloeServiceActor.scala
> +    addCSP {
Added CSP header to Swagger Related Paths!

2024-10-19 18:26 UTC, kevinmarete commented
> ## [Codecov](https://app.codecov.io/gh/broadinstitute/thurloe/pull/334?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=broadinstitute) Report
> Attention: Patch coverage is `57.69231%` with `11 lines` in your changes missing coverage. Please review.
> 
> > Project coverage is 59.34%. Comparing base [(`f27d5fe`)](https://app.codecov.io/gh/broadinstitute/thurloe/commit/f27d5fe12ece4258dff591d496f7ed50f05d58a5?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=broadinstitute) to head [(`8cec42e`)](https://app.codecov.io/gh/broadinstitute/thurloe/commit/8cec42edc2b41118aa3bc47ab83eb492fcbcfea9?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=broadinstitute).
> 
> [Files with missing lines](https://app.codecov.io/gh/broadinstitute/thurloe/pull/334?dropdown=coverage&src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=broadinstitute)	Patch %	Lines
> [...in/scala/thurloe/service/ThurloeServiceActor.scala](https://app.codecov.io/gh/broadinstitute/thurloe/pull/334?src=pr&el=tree&filepath=src%2Fmain%2Fscala%2Fthurloe%2Fservice%2FThurloeServiceActor.scala&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=broadinstitute#diff-c3JjL21haW4vc2NhbGEvdGh1cmxvZS9zZXJ2aWNlL1RodXJsb2VTZXJ2aWNlQWN0b3Iuc2NhbGE=)	56.52%	[10 Missing ⚠️ ](https://app.codecov.io/gh/broadinstitute/thurloe/pull/334?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=broadinstitute)
> [src/main/scala/thurloe/Main.scala](https://app.codecov.io/gh/broadinstitute/thurloe/pull/334?src=pr&el=tree&filepath=src%2Fmain%2Fscala%2Fthurloe%2FMain.scala&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=broadinstitute#diff-c3JjL21haW4vc2NhbGEvdGh1cmxvZS9NYWluLnNjYWxh)	0.00%	[1 Missing ⚠️ ](https://app.codecov.io/gh/broadinstitute/thurloe/pull/334?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=broadinstitute)
> Additional details and impacted files
> [☔ View full report in Codecov by Sentry](https://app.codecov.io/gh/broadinstitute/thurloe/pull/334?dropdown=coverage&src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=broadinstitute). 📢 Have feedback on the report? [Share it here](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=broadinstitute).

**Note:** Some of these changes were formatting related to scalafmt!

2024-10-21 13:11 UTC, dvoet requested changes
This code calls `addCSP` in 3 places, once in Main which covers all routes, then 2 other redundant times in `ThurloeServiceActor`.  I think it need only be called once but it makes more sense to have that be in `ThurloeServiceActor` where `route` is defined:
```
  def route: Route = addCSP {
    swaggerUiService ~ statusRoute ~ fireCloudProtectedRoutes
  }
```
Alternately, we could do this in the apache proxy.

2024-10-21 15:33 UTC, davidangb commented on src/main/scala/thurloe/service/ThurloeServiceActor.scala
> +  protected val swaggerUiPath = "META-INF/resources/webjars/swagger-ui/5.13.0"
if we're upgrading the swagger-ui version, can we go to latest 5.17.14?

2024-10-21 17:27 UTC, kevinmarete commented on src/main/scala/thurloe/service/ThurloeServiceActor.scala
> +  protected val swaggerUiPath = "META-INF/resources/webjars/swagger-ui/5.13.0"
Done: https://github.com/broadinstitute/thurloe/pull/334/commits/f20389f5d88ab9834f8eb5eb2ddf87d673bdad09

2024-10-21 18:08 UTC, dvoet approved these changes

2024-10-21 18:44 UTC, davidangb approved these changes

2024-10-21 18:56 UTC, merged