GAWB-1276: Allow thurloe to send notifications to external emails
broadinstitute/thurloe pull request #37
Opened 2016-11-22 14:44 UTC by MatthewBemis

This gives orchestration a way to specify an email directly and bypass the preferredEmail settings that won't exist for unregistered users.

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Make sure Swagger is updated if API changes
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2016-11-22 14:59 UTC, dvoet requested changes

2016-11-22 14:59 UTC, dvoet commented on src/main/scala/thurloe/dataaccess/SendGridDAO.scala
> +        Future.successful(notification.userEmail.getOrElse(throw new NotificationException("No recipient specified", Seq.empty, notification.notificationId)))
seems like you should use the email sent in the request over the preferred email, this does the opposite

2016-11-22 18:24 UTC, breilly2 commented on src/main/resources/swagger/thurloe.yaml
> -            "required": ["userId", "notificationId"],
The `Notification` case class looks like it still expects to always have a `notificationId`. Should it still be required?

2016-11-22 18:32 UTC, MatthewBemis commented on src/main/resources/swagger/thurloe.yaml
> -            "required": ["userId", "notificationId"],
Yes, dropped this by mistake

2016-11-22 18:47 UTC, breilly2 commented
👍 with update to make `notificationId` required again in swagger

2016-11-23 18:19 UTC, dvoet approved these changes
👍

2016-11-28 13:23 UTC, merged