Do not require FC header for /status (no JIRA)
broadinstitute/thurloe pull request #57
Opened 2017-11-10 01:25 UTC by aednichols

The `/status` endpoint shouldn't require the `X-FireCloud-Id` header. Right now it does.

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Make sure Swagger is updated if API changes
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via Slack and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2017-11-10 14:00 UTC, rushtong commented
This requires PO/FISMA/security approval. The FC ID header was added specifically to prevent any non-FC system.

2017-11-10 15:14 UTC, dvoet reviewed
The order should not matter and if it does then that is the actual bug.

2017-11-10 15:54 UTC, davidangb commented
I don't believe Thurloe's /status requires the `X-FireCloud-Id` header. I can hit it with swagger or curl and get a response just fine.

2017-11-13 15:22 UTC, aednichols commented
@davidangb, Bernick and Rob M. ran into an issue with a load balancer healthcheck that doesn't let you pass parameters:
```
curl https://thurloe201.dsde-dev.broadinstitute.org/status
```
returns
```
Missing 'X-FireCloud-Id' Header
```

@rushtong I think the status endpoint is protected only by accident; it's not in `fireCloudProtectedRoutes`, and the tests for it do not have a `addHeader` step. Does that change the required formalities? (I can see why it might not.)

2017-11-13 20:28 UTC, rushtong commented on src/main/scala/thurloe/service/ThurloeServiceActor.scala
> +      statusRoute
@aednichols - Can you test this without the swap? If it still works in the original, please revert.

2017-11-13 20:30 UTC, rushtong commented on src/main/scala/thurloe/service/ThurloeServiceActor.scala
> +      statusRoute
Ignore this, sorry.

2017-11-13 20:31 UTC, rushtong commented on src/main/scala/thurloe/service/ThurloeServiceActor.scala
> +
Revert please :-)

2017-11-13 20:37 UTC, rushtong approved these changes
👍

2017-11-13 20:43 UTC, aednichols commented
Talked to @davidbernick and he's cool with this for FISMA purposes (tagged him as reviewer as a courtesy).

2017-11-13 23:57 UTC, aednichols commented
I fixed the ignored test that let us miss this (by means of mock DAOs).

2017-11-14 13:38 UTC, davidangb requested changes
do not merge. There's something else fishy going on beyond the X-FireCloud-Id header, and we need to get to the bottom of it to understand the proper change to make.
```
curl https://thurloe201.dsde-dev.broadinstitute.org/status

Missing 'X-FireCloud-Id' Header
```
but:
```
curl -X GET --header "Accept: application/json" "https://thurloe201.dsde-dev.broadinstitute.org/status"

{"status": "up"}
```

possibly we are returning the "Missing 'X-FireCloud-Id' Header" error message in a case we shouldn't be?

Try this through swagger: https://thurloe.dsde-dev.broadinstitute.org/swagger/index.html?url=/swagger/thurloe.yaml#!/Status/status ... the status endpoint works just fine without the header. Note that swagger *does* send the `Accept` header. I realize the health check can't send the header, but we still need to figure out the right fix.

2017-11-14 15:23 UTC, davidangb commented
After running this locally, I see that your changes do in fact fix the issue. Could you explain them?

2017-11-14 16:30 UTC, aednichols commented
Sure. When we had
```
val fireCloudProtectedRoutes: Route = optionalHeaderValueByName(fcHeader) { [...] }
```
sending a `/status` request with no headers matched this route because the header is optional, and because this route comes before `statusRoute` in `ThurloeServiceActor.scala`. Once matched, we fell into the `None` case. You can verify this by changing line `18` of `FireCloudProtectedServices.scala` to
```
case None => respondWithStatus(StatusCodes.BadRequest) { complete("Jimmy") }
```
```
$ curl https://local.broadinstitute.org:40443/status
Jimmy
```

It doesn't really make sense to allow header-less requests to "fall into" this route only to immediately fail as a bad request, so I switched to `headerValueByName`. From its documentation,
```
If no header with a matching name is found the request is rejected with a [[spray.routing.MissingHeaderRejection]].
```

This causes the route not to match if there's no header, and Spray evaluation proceeds down to `statusRoute`.

2017-11-14 16:37 UTC, aednichols commented
The one thing I'm not sure about is what will happen when we send a `fireCloudProtectedRoutes` request with no FC header - will we get a useful error message? Will test with curl.

2017-11-14 17:03 UTC, davidangb approved these changes
:+1:

2017-11-14 19:32 UTC, davidangb approved these changes
:+1: once Travis tests pass

2017-11-14 19:37 UTC, merged